#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Narendra Bishnoi

echo "Answer the following questions:"
echo ""

read -p "1. Name one open-source tool you use daily: " TOOL
read -p "2. What does 'freedom' mean to you (one word)? " FREEDOM
read -p "3. What would you like to build and share? " BUILD

DATE=$(date '+%d %B %Y')
OUTPUT="manifesto_$(whoami).txt"

echo "--------------------------------------" > $OUTPUT
echo "Open Source Manifesto" >> $OUTPUT
echo "Date: $DATE" >> $OUTPUT
echo "" >> $OUTPUT

echo "I believe open source represents $FREEDOM." >> $OUTPUT
echo "Tools like $TOOL help developers learn and grow." >> $OUTPUT
echo "In the future, I want to build $BUILD and share it freely with the world." >> $OUTPUT

echo "" >> $OUTPUT
echo "— Generated by $(whoami)" >> $OUTPUT

echo "--------------------------------------"

echo "Manifesto saved in file: $OUTPUT"
echo ""
cat $OUTPUT
